### ISSUE TITLE
attempting Alphafold on Intel Xeon Silver 4210 CPU @ 2.20Ghz

### ISSUE THREAD

**Issue by avilella** [IntelLabs/Open-Omics-Acceleration-Framework#2]
I am interested in performing Alphafold2 for monomer proteins that are usually not very long, in the range of 250aa. We've been running these on 4GB VRAM Nvidia GPUs, but I wonder if this repo could also expand the calculations to other machines in our system, including the one detailed below.

Is there a rule of thumb on the CPU RAM usage compared to the GPU VRAM usage for Alphafold? Thx.

Here is my `cat /proc/cpuinfo` (20 cores):
```
processor       : 0
vendor_id       : GenuineIntel
cpu family      : 6
model           : 85
model name      : Intel(R) Xeon(R) Silver 4210 CPU @ 2.20GHz
stepping        : 7
microcode       : 0x5003303
cpu MHz         : 1000.104
cache size      : 14080 KB
physical id     : 0
siblings        : 20
core id         : 0
cpu cores       : 10
apicid          : 0
initial apicid  : 0
fpu             : yes
fpu_exception   : yes
cpuid level     : 22
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopolo
gy nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch
 cpuid_fault epb cat_l3 cdp_l3 invpcid_single intel_ppin ssbd mba ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid cqm mpx rdt_a avx512f avx512dq rd
seed adx smap clflushopt clwb intel_pt avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local dtherm ida arat pln pts hwp hwp_act_window hwp_epp hwp_pkg_req pku ospke avx512_
vnni md_clear flush_l1d arch_capabilities
bugs            : spectre_v1 spectre_v2 spec_store_bypass swapgs taa itlb_multihit mmio_stale_data retbleed eibrs_pbrsb
bogomips        : 4400.00
clflush size    : 64
cache_alignment : 64
address sizes   : 46 bits physical, 48 bits virtual
power management:

```

**Comment by sanchit-misra** [comment]
Hi Albert, thank you for your interest in this work. Yes, this pipeline should work on the CPU you have detailed. 
Regarding memory usage, we know that 750 aa protein only consumes about 10 GB in Evoformer inference. 250 aa should be even less.
Having said that, preprocessing also consumes memory. But you must be running it on CPU anyway. 

@narendrachaudhary51 can add more

**Comment by narendrachaudhary51** [comment]
Hi,

Our experiment for a 244 aa protein consumed ~7 GB of CPU RAM memory in the evoformer stage. However, preprocessing consumed ~54 GB of CPU RAM memory. It should be similar for you when running 250 aa proteins. We ran this experiment with baremetal code. Baremetal code is present in applications/alphafold folder of this repo.

**Comment by avilella** [comment]
Thanks, I got it running now, and I can confirm that the preprocessing with HHblits takes about 43Gb of CPU RAM in our setup:
![image](https://github.com/IntelLabs/Open-Omics-Acceleration-Framework/assets/158007/1527d257-063e-4b2d-9d7f-98312434f817)

**Comment by narendrachaudhary51** [comment]
Closing the issue as it has been resolved.
